In [1]:
import pandas as pd
import numpy as np


df = pd.read_csv("../data/dataset.csv")

TARGET = "CTR"

In [2]:
df.head()

,ID кампании,ID баннера,Тип баннера,Тип устройства,Показы,Переходы,CTR
0,3405596,15262577,interactive,Компьютер,12596,27,0.002144
1,3405596,15257617,interactive,Смартфон,9812,30,0.003057
2,3405596,15257617,interactive,Планшет,224,2,0.008929
3,3405596,15262577,interactive,Компьютер,12511,25,0.001998
4,3405596,15257617,interactive,Смартфон,9822,38,0.003869

In [3]:
df = df.dropna(subset=[TARGET])

In [4]:
df.head()

,ID кампании,ID баннера,Тип баннера,Тип устройства,Показы,Переходы,CTR
0,3405596,15262577,interactive,Компьютер,12596,27,0.002144
1,3405596,15257617,interactive,Смартфон,9812,30,0.003057
2,3405596,15257617,interactive,Планшет,224,2,0.008929
3,3405596,15262577,interactive,Компьютер,12511,25,0.001998
4,3405596,15257617,interactive,Смартфон,9822,38,0.003869